### ISSUE TITLE
USB flash and Vlan

### ISSUE THREAD

**Issue by qwertybuoisang** [leopardciaw/R619AC#1]
I installed this firmware, when i put USB flash in. This device can mount only under 8GB. not recognize USBflash 16 or 32GB.
and another problem is can not chang LAN "defaut" to another VLan . For example vlan 3.

**Comment by leopardciaw** [comment]
Sorry. Now, it is likely that you have installed the appropriate firmware.  Whether your router has been flashed to 128M mode, if it is already in this mode, please test other firmware.  The second question, because there is no test and use, can not be answered, I hope it has been resolved.
