### ISSUE TITLE
这个固件存在掉速问题

### ISSUE THREAD

**Issue by Benjamin23333** [leopardciaw/R619AC#1]
我在刷了这个项目的固件之后，会出现网速在刚刷完时速度跑满，而在隔几个小时后再测速时出现掉速，刷了其他的固件并没有出现这种情况

**Comment by leopardciaw** [comment]
不好意思，刚看到信息。我没有测试掉速情况，根据lede源代码来编译的。您那掉速后，后来会正常吗，现在有无解决方法分享。

**Comment by Benjamin23333** [comment]
对不起，因为我又买了r2s，取代了原本竞斗云主路由的位置，所以竞斗云刷了x-wrt做了ap，已经不用您的固件了。掉速问题是出现在用几个小时后，正常情况下，开了acc加速，我的网速是在45m/s左右，几个小时候会掉到36-39左右，第二天会掉到18-20左右。解决方法没有找到就换了设备。

**Comment by leopardciaw** [comment]
我看能否找到原因。依然感谢，一切顺利！
