### ISSUE TITLE
希望加入EasyMesh

### ISSUE THREAD

**Issue by zsinba** [leopardciaw/R619AC#10]
希望作者能加入EasyMesh的插件。

**Comment by leopardciaw** [comment]
抱歉才回复。
已在r619ac.config里增加CONFIG_PACKAGE_luci-app-easymesh=y，看下编译固件的效果如何哈。

**Comment by zsinba** [comment]
还有没机会试， 我拿到 设备再试试。谢谢

**Comment by zsinba** [comment]
已确认，EasyMesh可用。
