### ISSUE TITLE
请问如何安装USB打印机服务

### ISSUE THREAD

**Issue by KaneOne** [leopardciaw/R619AC#4]
大佬，请问如何开启USB打印机的功能，感谢~

**Comment by leopardciaw** [comment]
抱歉，刚注意到问题。可以在r619ac.config里将# CONFIG_PACKAGE_luci-app-usb-printer is not set，修改为：CONFIG_PACKAGE_luci-app-usb-printer=y，会编译出包含这个的固件，怎么使用，你再探索下哈。

**Comment by KaneOne** [comment]
> 抱歉，刚注意到问题。可以在r619ac.config里将# CONFIG_PACKAGE_luci-app-usb-printer is not set，修改为：CONFIG_PACKAGE_luci-app-usb-printer=y，会编译出包含这个的固件，怎么使用，你再探索下哈。

谢谢 前几天我自己试着修改了这个配置编译 但是编译好几个小时到后半段报错没有继续了

**Comment by leopardciaw** [comment]
> > 抱歉，刚注意到问题。可以在r619ac.config里将# CONFIG_PACKAGE_luci-app-usb-printer is not set，修改为：CONFIG_PACKAGE_luci-app-usb-printer=y，会编译出包含这个的固件，怎么使用，你再探索下哈。
> 
> 谢谢 前几天我自己试着修改了这个配置编译 但是编译好几个小时到后半段报错没有继续了

我编译看下，是否报错哈。

**Comment by leopardciaw** [comment]
> > 抱歉，刚注意到问题。可以在r619ac.config里将# CONFIG_PACKAGE_luci-app-usb-printer is not set，修改为：CONFIG_PACKAGE_luci-app-usb-printer=y，会编译出包含这个的固件，怎么使用，你再探索下哈。
> 
> 谢谢 前几天我自己试着修改了这个配置编译 但是编译好几个小时到后半段报错没有继续了

昨晚编译成功了，没有出现错误，你看下我的config和固件。

**Comment by KaneOne** [comment]
感谢 今天看到安装您编译的新固件 刷新后出现USB打印机功能了 也可以自动侦测到打印机类型 不过电脑上安装打印机后无法打印 我继续研究一下。编译的问题不知道是不是我用的WIN10的LINUX子系统的缘故。

**Comment by leopardciaw** [comment]
> 感谢 今天看到安装您编译的新固件 刷新后出现USB打印机功能了 也可以自动侦测到打印机类型 不过电脑上安装打印机后无法打印 我继续研究一下。编译的问题不知道是不是我用的WIN10的LINUX子系统的缘故。

抱歉，我没有安装和使用这个插件，无法给出实践建议哈，搜索下网络看。
